/**
 * GET /docs — interactive Scalar UI for the API spec (#143).
 *
 * The spec itself is generated by `apps/api/scripts/gen-openapi.ts`
 * and committed to `docs/openapi.yml`. At process start we:
 *
 *   1. Load every `*.openapi.ts` so the registry is fully populated.
 *   2. Generate the same OpenAPI document the CI / CLI generator
 *      emits — re-using `OpenApiGeneratorV31` keeps a single source
 *      of truth for spec shape between the served + committed copies.
 *   3. Serve the JSON document at `/docs/openapi.json` and a Scalar
 *      HTML viewer at `/docs`.
 *
 * Scalar is loaded from a CDN <script> tag so we don't pull a
 * second copy of React into the API process.
 */

import { Router } from "express";
import { OpenApiGeneratorV31 } from "@asteasolutions/zod-to-openapi";
import { registry, loadAllRouteSchemas } from "@/lib/openapi-registry";

const router = Router();

let cachedDocument: unknown | null = null;

async function buildDocument(): Promise<unknown> {
  if (cachedDocument) return cachedDocument;
  await loadAllRouteSchemas();
  registry.registerComponent("securitySchemes", "bearerAuth", {
    type: "http",
    scheme: "bearer",
    bearerFormat: "JWT",
  });
  const generator = new OpenApiGeneratorV31(registry.definitions);
  cachedDocument = generator.generateDocument({
    openapi: "3.1.0",
    info: {
      title: "BrandBlitz API",
      version: process.env.npm_package_version || "0.1.0",
    },
  });
  return cachedDocument;
}

router.get("/openapi.json", async (_req, res, next) => {
  try {
    res.json(await buildDocument());
  } catch (err) {
    next(err);
  }
});

router.get("/", async (_req, res, next) => {
  try {
    // Pre-warm so the first /docs hit doesn't race the JSON request
    // from Scalar.
    await buildDocument();
    res.type("html").send(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>BrandBlitz API</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>body { margin: 0 }</style>
  </head>
  <body>
    <script
      id="api-reference"
      data-url="/docs/openapi.json"
      data-configuration='{"theme":"default","layout":"modern"}'
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>`);
  } catch (err) {
    next(err);
  }
});

export default router;
